### ISSUE TITLE
undefined: gabs.Consume

### ISSUE THREAD

**Issue by FilipeBorges1993** [gen0cide/gscript#115]
The console are return this when run gscript shell:

gen0cide/gscript/stdlib/requests/requests.go:129:18: undefined: gabs.Consume
[gscript:cli] ERROR Build Dir Located At: /tmp/ndvgEoICAVjFSofz
[gscript:cli] FATAL Error Encountered: exit status 2

**Comment by kernel-sanders** [comment]
I believe this was fixed by #114

**Comment by vyrus001** [comment]
The docker fix adjusted the version issue but did not fix the fact that the API for gabs has changed in a breaking way. I just submitted a pr to fix it for real.

**Comment by vyrus001** [comment]
just fixed this as well as upgrading gab to latest version
